apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: nginx
spec:
  replicas: {{ .Values.replicaCount }} // # 5 ta
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
          name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" // # nginx:1.16.0
          imagePullPolicy: {{ .Values.image.pullPolicy }} // # IfNoheltPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP